
// https:newsapi.org/v2/top-headlines?
// country=eg&category=business&apiKey=65f7f556ec76449fa7dc7c0069f040ca


// {

//     "status":"ok",
//     "totalResults":70,
//     "articles":[
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"Sky News Arabia سكاي نيوز عربية",
//       "title":"إيلون ماسك يهاجم واتساب بسبب \"الميكروفون السري\" - Sky News Arabia سكاي نيوز عربية",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMipwJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS90ZWNobm9sb2d5LzE2MTkzMTQtJUQ4JUE3JUQ5JTk1JUQ5JThBJUQ5JTg0JUQ5JTg4JUQ5JTg2LSVEOSU4NSVEOCVBNyVEOCVCMyVEOSU4My0lRDklOEElRDklODclRDglQTclRDglQUMlRDklODUtJUQ5JTg4JUQ4JUE3JUQ4JUFBJUQ4JUIzJUQ4JUE3JUQ4JUE4LSVEOCVBOCVEOCVCMyVEOCVBOCVEOCVBOC0lRDglQTclRDklODQlRDklODUlRDklOEElRDklODMlRDglQjElRDklODglRDklODElRDklODglRDklODYtJUQ4JUE3JUQ5JTg0JUQ4JUIzJUQ4JUIxJUQ5JThB0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T16:31:06Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"كوميرز بنك يتوقع استقرار سعر الذهب عند هذا المستوى! بواسطة المتداول العربي - السعودية Investing.comالسعودية Investing.com",
//       "description":null,"url":"https://news.google.com/rss/articles/CBMiPmh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2NvbW1vZGl0aWVzLW5ld3MvYXJ0aWNsZS0yNDEyMDkw0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T16:09:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"Al Masry Al Youm - المصري اليوم",
//       "title":"ارتفاع في عيار 21 الآن.. سعر الذهب اليوم الثلاثاء 9-5-2023 في الصاغة - Al Masry Al Youm - المصري اليوم",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiMmh0dHBzOi8vd3d3LmFsbWFzcnlhbHlvdW0uY29tL25ld3MvZGV0YWlscy8yODgyNjQ20gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T15:08:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"عاجل: الأسهم تتحرك للأسفل بفعل أحداث هامة.. هبوط النفط وارتفاع الدولار وتخبط الذهب بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiP2h0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL3N0b2NrLW1hcmtldC1uZXdzL2FydGljbGUtMjQxMjA0ONIBAA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T14:58:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"عاجل: تصريحات هامة من الفيدرالي الأمريكي بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiNWh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2Vjb25vbXkvYXJ0aWNsZS0yNDExOTY20gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T13:04:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"خبير: حان الآن وقت اندفاع الذهب نحو قمة الـ 2200.. لن يعود أدنى 2000 مجددًا بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiPmh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2NvbW1vZGl0aWVzLW5ld3MvYXJ0aWNsZS0yNDExOTUy0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T12:25:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"نجوم مصرية",
//       "title":"\"لينكد إن\" توقف شبكتها الاجتماعية في الصين.. ما السبب وراء ذلك؟! - نجوم مصرية",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMi3AFodHRwczovL3d3dy5uZ21pc3IuY29tL3RlY2gvJUQ5JTg0JUQ5JThBJUQ5JTg2JUQ5JTgzJUQ4JUFGLSVEOCVBNSVEOSU4Ni0lRDglQUElRDklODglRDklODIlRDklODEtJUQ4JUI0JUQ4JUE4JUQ5JTgzJUQ4JUFBJUQ5JTg3JUQ4JUE3LSVEOCVBNyVEOSU4NCVEOCVBNyVEOCVBQyVEOCVBQSVEOSU4NSVEOCVBNyVEOCVCOSVEOSU4QSVEOCVBOS0lRDklODElRDklOEEtJUQ4JUE3JUQ5JTg00gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T12:17:01Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"بنك أوف أمريكا يوضح التهديد الأكبر لهيمنة الدولار.. ليس اليوان أو البريكس! بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiOGh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2ZvcmV4LW5ld3MvYXJ0aWNsZS0yNDExODg10gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T11:46:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"جريدة المال","title":"«ماريدايف» توافق علي صفقة استحواذ «الجهاز السعودية» على شركتها التابعة مقابل 115.6 مليون دولار - جريدة المال",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMixAFodHRwczovL2FsbWFsbmV3cy5jb20vJUQ5JTg1JUQ4JUE3JUQ4JUIxJUQ5JThBJUQ4JUFGJUQ4JUE3JUQ5JThBJUQ5JTgxLSVEOCVBQSVEOSU4OCVEOCVBNyVEOSU4MSVEOSU4Mi0lRDglQjklRDklODQlRDklOEEtJUQ4JUI1JUQ5JTgxJUQ5JTgyJUQ4JUE5LSVEOCVBNyVEOCVCMyVEOCVBQSVEOCVBRCVEOSU4OCVEOCVBNyVEOCVCMC0lRDglQTcv0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T11:11:23Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"العربية","title":"بالأرقام.. أكبر الدول امتلاكاً للأقمار الصناعية في الفضاء - العربية",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMi4gJodHRwczovL3d3dy5hbGFyYWJpeWEubmV0L2Fzd2FxL3NwZWNpYWwtc3Rvcmllcy8yMDIzLzA1LzA5LyVEOCVBOCVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCMSVEOSU4MiVEOCVBNyVEOSU4NS0lRDglQTMlRDklODMlRDglQTglRDglQjEtJUQ4JUE3JUQ5JTg0JUQ4JUFGJUQ5JTg4JUQ5JTg0LSVEOCVBNyVEOSU4NSVEOCVBQSVEOSU4NCVEOCVBNyVEOSU4MyVEOCVBNyVEOSU4Qi0lRDklODQlRDklODQlRDglQTMlRDklODIlRDklODUlRDglQTclRDglQjEtJUQ4JUE3JUQ5JTg0JUQ4JUI1JUQ5JTg2JUQ4JUE3JUQ4JUI5JUQ5JThBJUQ4JUE5LSVEOSU4MSVEOSU4QS0lRDglQTclRDklODQlRDklODElRDglQjYlRDglQTclRDglQTHSAeYCaHR0cHM6Ly93d3cuYWxhcmFiaXlhLm5ldC9hbXAvYXN3YXEvc3BlY2lhbC1zdG9yaWVzLzIwMjMvMDUvMDkvJUQ4JUE4JUQ4JUE3JUQ5JTg0JUQ4JUEzJUQ4JUIxJUQ5JTgyJUQ4JUE3JUQ5JTg1LSVEOCVBMyVEOSU4MyVEOCVBOCVEOCVCMS0lRDglQTclRDklODQlRDglQUYlRDklODglRDklODQtJUQ4JUE3JUQ5JTg1JUQ4JUFBJUQ5JTg0JUQ4JUE3JUQ5JTgzJUQ4JUE3JUQ5JThCLSVEOSU4NCVEOSU4NCVEOCVBMyVEOSU4MiVEOSU4NSVEOCVBNyVEOCVCMS0lRDglQTclRDklODQlRDglQjUlRDklODYlRDglQTclRDglQjklRDklOEElRDglQTktJUQ5JTgxJUQ5JThBLSVEOCVBNyVEOSU4NCVEOSU4MSVEOCVCNiVEOCVBNyVEOCVBMQ?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T10:42:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"جي بي مورغان: الفائدة ستنخفض في هذين الحالتين فقط.. والأسواق ترفض الاعتراف بهما! بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiP2h0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL3N0b2NrLW1hcmtldC1uZXdzL2FydGljbGUtMjQxMTc4NtIBAA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T10:23:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"النيل الإخباري","title":"بالصور مواصفات تويوتا كورولا 2024 الجديدة كليا والأسعار المتوقعة - النيل الإخباري",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMi4QFodHRwczovL3d3dy5uaWxlNC5jb20vMjg2MjY2LyVEOCVBOCVEOCVBNyVEOSU4NCVEOCVCNSVEOSU4OCVEOCVCMS0lRDklODUlRDklODglRDglQTclRDglQjUlRDklODElRDglQTclRDglQUEtJUQ4JUFBJUQ5JTg4JUQ5JThBJUQ5JTg4JUQ4JUFBJUQ4JUE3LSVEOSU4MyVEOSU4OCVEOCVCMSVEOSU4OCVEOSU4NCVEOCVBNy0yMDI0LSVEOCVBNyVEOSU4NCVEOCVBQyVEOCVBRiVEOSU4QSVEOCVBRi_SAQA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T09:43:20Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"إفلاس جديد لبورصة عملات رقمية شهيرة يضرب سوق الكريبتو.. وتراجع جماعي بالسوق بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiQWh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2NyeXB0b2N1cnJlbmN5LW5ld3MvYXJ0aWNsZS0yNDExNzIx0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T09:25:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"Masrawy - مصراوي",
//       "title":"يصل لـ500 ألف جنيه.. تفاصيل قرض تمويل شراء الأجهزة الكهربائية في 3 بنوك - Masrawy - مصراوي",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiQ2h0dHBzOi8vd3d3Lm1hc3Jhd3kuY29tL25ld3MvbmV3cy1iYW5raW5nL2RldGFpbHMvMjAyMy80LzIvMjQxMDYzNi_SAZUDaHR0cHM6Ly93d3cubWFzcmF3eS5jb20vbmV3cy9uZXdzLWJhbmtpbmcvZGV0YWlscy8yMDIzLzUvOS8yNDEwNjM2LyVEOSU4QSVEOCVCNSVEOSU4NC0lRDklODQlRDklODA1MDAtJUQ4JUEzJUQ5JTg0JUQ5JTgxLSVEOCVBQyVEOSU4NiVEOSU4QSVEOSU4Ny0lRDglQUElRDklODElRDglQTclRDglQjUlRDklOEElRDklODQtJUQ5JTgyJUQ4JUIxJUQ4JUI2LSVEOCVBQSVEOSU4NSVEOSU4OCVEOSU4QSVEOSU4NC0lRDglQjQlRDglQjElRDglQTclRDglQTEtJUQ4JUE3JUQ5JTg0JUQ4JUEzJUQ4JUFDJUQ5JTg3JUQ4JUIyJUQ4JUE5LSVEOCVBNyVEOSU4NCVEOSU4MyVEOSU4NyVEOCVCMSVEOCVBOCVEOCVBNyVEOCVBNiVEOSU4QSVEOCVBOS0lRDklODElRDklOEEtMy0lRDglQTglRDklODYlRDklODglRDklODM_YW1w?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T09:19:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"المستقبل","title":"البريد المصري يعلن الفائدة الجديدة على حساب التوفير الجديد - المستقبل",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiI2h0dHBzOi8vd3d3LmVsbW9zdGFxYmFsLmNvbS82OTMyNzcv0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T09:16:47Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"الأسبوع","title":"عز يتخطى 41 ألف جنيها.. أسعار الحديد والأسمنت اليوم الثلاثاء 9 مايو 2023 - الأسبوع",
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiIGh0dHBzOi8vd3d3LmVsYW9zYm9hLmNvbS84OTQwODUv0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T08:45:38Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"احذر الذهب وقرارات مصيرية..قد يهبط أدنى 1950 دولارًا إذا حدث ذلك - السعودية Investing.comالسعودية Investing.com",
//       "description":null,"url":"https://news.google.com/rss/articles/CBMiM2h0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9hbmFseXNpcy9hcnRpY2xlLTIwMDQ3NjkyM9IBAA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T08:33:00Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"news.5lejnews.com","title":"إحجز .. عروض بيم بخصومات خيالية علي كافة السلع لشهر مايو 2023 - news.5lejnews.com"
//       "description":null,
//       "url":"https://news.google.com/rss/articles/CBMiT2h0dHBzOi8vbmV3cy41bGVqbmV3cy5jb20vNjcxNDAvJUQ4JUI5JUQ4JUIxJUQ5JTg4JUQ4JUI2LSVEOCVBOCVEOSU4QSVEOSU4NS0yNS_SAQA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T07:53:14Z",
//       "content":null},
    
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"السعودية Investing.comالسعودية Investing.com",
//       "title":"الفيدرالي يتحدث.. الاقتصاد في طريقه للسقوط في بئر الركود لهذه الأسباب! بواسطة Investing.com - السعودية Investing.comالسعودية Investing.com",
//       "description":null,"url":"https://news.google.com/rss/articles/CBMiNWh0dHBzOi8vc2EuaW52ZXN0aW5nLmNvbS9uZXdzL2Vjb25vbXkvYXJ0aWNsZS0yNDExNjc00gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T07:53:00Z",
//       "content":null},
      
//       {"source":{"id":"google-news","name":"Google News"},
//       "author":"Al Masry Al Youm - المصري اليوم",
//       "title":"ارتفاع مؤشرات البورصة في بداية تداولات اليوم - Al Masry Al Youm - المصري اليوم",
//       "description":null,"url":"https://news.google.com/rss/articles/CBMiMmh0dHBzOi8vd3d3LmFsbWFzcnlhbHlvdW0uY29tL25ld3MvZGV0YWlscy8yODgyMjUz0gEA?oc=5",
//       "urlToImage":null,
//       "publishedAt":"2023-05-09T07:27:00Z",
//       "content":null}]
     
    
// }  